# Generated by Django 4.2.3 on 2023-12-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedirectory',
            name='persona',
            field=models.ForeignKey(blank=True, db_column='persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate_app.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='persona',
            field=models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2')], max_length=255),
        ),
    ]
